@startuml

Vehicle --o Parking

Vehicle : -Registration
Vehicle : -CarType
Vehicle : -Clock EntranceTime
Vehicle : -Clock DepartureTime
Vehicle : +Vehicle()
Vehicle : +VehicleInfo()

Clock : -Minute
Clock : -Hour
Clock : -Day
Clock : +Clock()
Clock : +void Tick()
Clock : +string Display()

Clock --o Parking

Parking : -Time
Parking : -CarList
Parking : -MaximumCapacity
Parking : -ActualCapacity
Parking : -Raport
Parking : +Parking()
Parking : +void Entrance(Vehicle v)
Parking : +void Departure(Vehicle v)
Parking : +void ParkingCurrentStatus()

Raport : -DailyRaport
Raport : +Raport()
Raport : +void AddVehicle()
Raport : +void CleanDailyRaport()
Raport : +void DisplayDailyRaport()
Raport : +void DisplayHistory()

Raport --o Parking


enum CarTypes {
    Passenger Car
    Delivery Truck
    Truck
}

@enduml